# Generated by Django 3.1 on 2020-09-02 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upvotes',
            new_name='votes',
        ),
    ]
