version: '3.8'

services:
    web:
        build: .
        command: gunicorn news_site.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - .:/home/roombambar/Desktop/project_news/news_site
        ports:
            - 8000:8000
        env_file: .env
        depends_on: 
            - db
    db:
        image: postgres
        env_file: .env-db
        volumes:
            - ./postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432

volumes:
    posgres_data:
